export const getRouteMain = () => '/';
export const getRouteAuth = () => '/auth';
export const getRouteDashboard = () => '/dashboard';
export const getRouteExpenses = () => '/expenses';
export const getRouteIncomes = () => '/incomes';
export const getRouteCreditAndDebt = () => '/credit_and_debt';
export const getRouteFinancialGoals = () => '/financial_goals';
export const getRouteBudgetPlans = () => '/budget_plans';
export const getRouteInvestments = () => '/investments';
export const getRouteInvestmentDetails = (id: string) => `/investments/${id}`;
export const getRouteForbidden = () => '/forbidden';
