export enum AppRoutes {
  // MAIN = 'main',
  AUTH = 'auth',
  DASHBOARD = 'dashboard',
  EXPENSES = 'expenses',
  // EXPENSE_DETAILS = 'expense_details',
  INCOMES = 'incomes',
  // INCOMES_DETAILS = 'incomes_details',
  CREDIT_AND_DEBT = 'credit_and_debt',
  CREDIT_DETAILS = 'credit_details',
  DEBT_DETAILS = 'debt_details',
  FINANCIAL_GOALS = 'financial_goals',
  FINANCIAL_GOAL_DETAILS = 'financial_goal_details',
  BUDGET_PLANS = 'budget_plans',
  BUDGET_PLAN_DETAILS = 'budget_plan_details',
  INVESTMENTS = 'investments',
  INVESTMENT_DETAILS = 'investment_details',
  NOT_FOUND = 'not_found',
  FORBIDDEN = 'forbidden',
}
