'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { MantineProvider } from '@/app/providers/MantineProvider';
import { StoreProvider } from '@/app/providers/StoreProvider';
import { AppShell, Loader, useMantineTheme } from '@mantine/core';
import { Navbar } from '@/widgets/Navbar';
import { Header } from '@/widgets/Header';
import { Suspense, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const theme = useMantineTheme();
  const [opened, setOpened] = useState(false);

  const mantineStyles = {
    main: {
      background: theme.colorScheme === 'dark' ? theme.colors.gray[0] : theme.colors.dark[8],
    },
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loader />}>
          <MantineProvider>
            <StoreProvider>
              <AppShell
                styles={mantineStyles}
                navbarOffsetBreakpoint="sm"
                asideOffsetBreakpoint="sm"
                navbar={<Navbar opened={opened} />}
                header={<Header opened={opened} setOpened={setOpened} />}
              >
                {children}
              </AppShell>
            </StoreProvider>
          </MantineProvider>
        </Suspense>
      </body>
    </html>
  );
}
