version: '3'
services:
  postgres:
    image: postgres
    container_name: financial-tracker-db
    env_file:
      - .env
    environment:
      - PG_DATA=${POSTGRES_DATA}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - pgdata:${POSTGRES_DATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
volumes:
  pgdata:
