name: app-ci

on:
  push:
    branches: [ test_deploy ]


jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: cd ./server
      - run: npm i
      - run: npm run test 
