name: tests-and-linters

on:
  pull_request:
    branches: [ dev ]

defaults:
  run:
    working-directory: client

jobs:
  tests-and-linters:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Fontend install deps
        run: npm i
      - name: Frontend Lint checks
        run: npm run lint:ts
      - name: Frontend Unit tests
        run: npm run test:unit
      - name: Backend install deps
        run: yarn
      - name: Backend lint checks
        run: cd ./server && npm run lint
      - name: Backend Unit tests
        run: npm run test
      - run: cd ./server && npm run test
