name: ci-cd

on:
  pull_request:
    branches: [ dev ]
  push:
      branches: [ refactoring-ci-cd ]

jobs:
  tests-and-linters:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: cd ./client && npm i && npm run test:unit
      - run: cd ./server && npm i && npm run test
